### ISSUE TITLE
App freeze after recent update

### ISSUE THREAD

**Issue by algernon-A** [sway2020/FindIt2#62]
Two users report intermittent app freeze after recent update (presumably specifically d279b38b2812429d5586bf00a41c43e2b3fea08c causing the issues).

Unable to reproduce, but assuming most likely candidate is legacy code (UIView check) fragment.

Using this issue to track success (or otherwise) of attempted fixes.  If issue can't be fixed quickly, will revert to legacy code until the issue can be pinpointed.

**Comment by algernon-A** [comment]
Putative fix in 1795b90b341c86da92c8f09c80fc8538b5704c9f

**Comment by sway2020** [comment]
1795b90 fix included in v 1.7.0-2 release

**Comment by sway2020** [comment]
It seems like the issue is on thumbnail generation, not input detection.

https://github.com/sway2020/CS-FindIt/blob/d6117d831a53c1c1e713b71da489a796a78c901f/FindIt/GUI/ThumbnailManager.cs#L103-L143

This method causes stack overflows when it tries to generate thumbnails for some assets. 
Example asset: https://steamcommunity.com/sharedfiles/filedetails/?id=407030135

**Comment by sway2020** [comment]
That example asset doesn't have any mesh or material.

**Comment by algernon-A** [comment]
Confirmed issue was stack overflow caused by infinite loop between UIFastList.Display and FixThumbnails for assets with no mesh, material, atlas or thumbnail.

Fixed in 7e1208a348e7578acc77b7af6eb5c0736db44cb7
