### ISSUE TITLE
Top/recent/favorite searches "filter" ?

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#81]
Perhaps it would be handy to have some kind top/recent/favorite searches. Which would also automatically select the right category/filters.

**Comment by sway2020** [comment]
Both the original Find It and this version perform a new search every time a character is entered. So when a user searches for "abcde" the mod performs 5 searches of a, ab, abc, abcd, abcde. This new feature will need a timer running behind the scene to detect the time interval between keystrokes in order to identify the actual intended search term.

**Comment by sway2020** [comment]
This requires some great changes to the current search algorithm. Probably won't be worked on.
