### ISSUE TITLE
Unused workshop ID's

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#90]
Hi i really love the unussed asset feature. One thing is sometimes a bit challenging is that some unused assets are part of a pack (single workshop ID).

It would be handy if we could get someking of list of unused Workshop ID's, so we can safely unsubscribe from them.

**Comment by sway2020** [comment]
I think this can be implemented in this way: adding an "export unused workshop id list" button somewhere and it will export and save the links in an html file with hyperlinks, similar to what the Loading Screen Mod does with missing dependency assets? The html file can have two sections like this:

Filename: FindItUnusedWorkshopItems_CityName_DateTime.html

[Not used]

Workshop ID 123455
(link)

Workshop ID 123592
(link)


[Only partially used]

Workshop ID 232323, 2 of 12 assets are used in this pack
(link)

Workshop ID 3498793, 1 of 5 assets are used in this pack
(link)

**Comment by sway2020** [comment]
@Sipke82 I just realized the Loading Screen Mod already can generate a list of unused assets and export it into an HTML file. It is not a list of unused Workshop ID tho but I think that mod can be easily modified to achieve it. I think it might be better to send a request to the author of the Loading Screen Mod?

**Comment by Sipke82** [comment]
Yes perhaps thats a better place. I discussed it in the workshop comments with Thale, but it seemed like he aint got time to implemenent currentlly...

Ill make a issue on the LSM github.

**Comment by sway2020** [comment]
It also can be done in Find It but it will take some time because I'll need to write the code from scratch. Also Find It doesn't deal with citizen and vehicle assets(but LSM does). But one thing Find It does better is that currently Find It also checks procedural objects dependency which I think LSM doesn't. I think this is better to be done in LSM because it is more related to "asset loading", but if Thale says he's too busy I can also implement this in Find It.

**Comment by sway2020** [comment]
@Sipke82  It also can be done in Find It but it will take some time because I'll need to write more code. Also Find It doesn't deal with citizen and vehicle assets(but LSM does). But one thing Find It does better is that currently Find It also checks procedural objects dependency which I think LSM doesn't. I think this is better to be done in LSM because it is more related to "asset loading", but if Thale says he's too busy I can also implement this in Find It. Let me know when you get a reply from Thale.

**Comment by Sipke82** [comment]
not possible?

**Comment by sway2020** [comment]
There were some technical stuff that I wasn't able to finish and I'm quite busy irl so this probably won't be worked on any time soon. I closed it just to avoid any false hope. Maybe I should reopen it and add a new "help wanted" label. Maybe some other modders will step in

**Comment by sway2020** [comment]
@Sipke82 It's finished and it will be included in the next update of the beta release

**Comment by Sipke82** [comment]
Amazing! thank you so much!!!

One question, does it recognize if a workshop id is used for  a PO?

Op vr 20 nov. 2020 om 20:47 schreef sway2020 <notifications@github.com>:

**Comment by sway2020** [comment]
It does consider POs as long as the "include PO" option in the quick menu is enabled. It doesn't work well with assets that are bundled with mods because each mod may use the assets for different purposes. For example Network Extension 2's roads are set to be vanilla with no workshop id, but the road props are custom with workshop id. Elektrix's Tree and Vehicle Prop mod has a prop that the mod uses as a conversion template, if you delete the prop the mod will fail. When you open the workshop page of a workshop id and it turns out to be a mod, it's better to just ignore it.
